#############################################################################
# Makefile for building: ATM.app/Contents/MacOS/ATM
# Generated by qmake (3.1) (Qt 6.2.4)
# Project:  ../ATM/ATM.pro
# Template: app
# Command: /Users/macbook/Desktop/QT/6.2.4/macos/bin/qmake -o Makefile ../ATM/ATM.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I../ATM -I. -I../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers -I../Desktop/QT/6.2.4/macos/lib/QtGui.framework/Headers -I../Desktop/QT/6.2.4/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I../Desktop/QT/6.2.4/macos/mkspecs/macx-clang -F/Users/macbook/Desktop/QT/6.2.4/macos/lib
QMAKE         = /Users/macbook/Desktop/QT/6.2.4/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/macbook/Desktop/QT/6.2.4/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/macbook/Desktop/QT/6.2.4/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ATM1.0.0
DISTDIR = /Users/macbook/build-ATM-Qt_6_2_4_for_macOS-Debug/.tmp/ATM1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/macbook/Desktop/QT/6.2.4/macos/lib
LIBS          = $(SUBLIBS) -F/Users/macbook/Desktop/QT/6.2.4/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../ATM/main.cpp \
		../ATM/mainwindow.cpp \
		../ATM/transactions.cpp moc_mainwindow.cpp \
		moc_transactions.cpp
OBJECTS       = main.o \
		mainwindow.o \
		transactions.o \
		moc_mainwindow.o \
		moc_transactions.o
DIST          = ../Desktop/QT/6.2.4/macos/mkspecs/features/spec_pre.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/device_config.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/unix.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/mac.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/macx.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/sanitize.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/gcc-base.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/gcc-base-mac.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/clang.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/clang-mac.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/qconfig.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_core.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designer.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_gui.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_help.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_network.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qml.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quick.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_sql.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svg.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_xml.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qt_functions.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qt_config.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/macx-clang/qmake.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/spec_post.prf \
		../ATM/.qmake.stash \
		../Desktop/QT/6.2.4/macos/mkspecs/features/exclusive_builds.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/sdk.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/toolchain.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/toolchain.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/default_pre.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/default_pre.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/resolve_config.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/default_post.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/default_post.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/objective_c.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qml_debug.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/mac.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/warn_on.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qt.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/resources_functions.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/resources.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/moc.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/unix/opengl.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/uic.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/unix/thread.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qmake_use.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/file_copies.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/rez.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/testcase_targets.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/exceptions.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/yacc.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/lex.prf \
		../ATM/ATM.pro ../ATM/mainwindow.h \
		../ATM/transactions.h ../ATM/main.cpp \
		../ATM/mainwindow.cpp \
		../ATM/transactions.cpp
QMAKE_TARGET  = ATM
DESTDIR       = 
TARGET        = ATM.app/Contents/MacOS/ATM

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/macbook/build-ATM-Qt_6_2_4_for_macOS-Debug/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/macbook/ATM/ATM.pro


include /Users/macbook/Desktop/QT/6.2.4/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

ATM.app/Contents/MacOS/ATM: ui_mainwindow.h ui_transactions.h $(OBJECTS)  
	@test -d ATM.app/Contents/MacOS/ || mkdir -p ATM.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../ATM/ATM.pro ../Desktop/QT/6.2.4/macos/mkspecs/macx-clang/qmake.conf ../Desktop/QT/6.2.4/macos/mkspecs/features/spec_pre.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/device_config.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/unix.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/mac.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/macx.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/sanitize.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/gcc-base.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/gcc-base-mac.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/clang.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/common/clang-mac.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/qconfig.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_core.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designer.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_gui.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_help.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_network.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qml.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quick.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_sql.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svg.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_xml.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qt_functions.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qt_config.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/macx-clang/qmake.conf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Desktop/QT/6.2.4/macos/mkspecs/features/exclusive_builds.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/sdk.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/toolchain.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/toolchain.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/default_pre.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/default_pre.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/resolve_config.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/default_post.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/default_post.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/objective_c.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qml_debug.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/mac.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/warn_on.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qt.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/resources_functions.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/resources.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/moc.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/unix/opengl.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/uic.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/unix/thread.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/qmake_use.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/file_copies.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/rez.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/testcase_targets.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/exceptions.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/yacc.prf \
		../Desktop/QT/6.2.4/macos/mkspecs/features/lex.prf \
		../ATM/ATM.pro \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../Desktop/QT/6.2.4/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../Desktop/QT/6.2.4/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../ATM/ATM.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../Desktop/QT/6.2.4/macos/mkspecs/features/spec_pre.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/device_config.prf:
../Desktop/QT/6.2.4/macos/mkspecs/common/unix.conf:
../Desktop/QT/6.2.4/macos/mkspecs/common/mac.conf:
../Desktop/QT/6.2.4/macos/mkspecs/common/macx.conf:
../Desktop/QT/6.2.4/macos/mkspecs/common/sanitize.conf:
../Desktop/QT/6.2.4/macos/mkspecs/common/gcc-base.conf:
../Desktop/QT/6.2.4/macos/mkspecs/common/gcc-base-mac.conf:
../Desktop/QT/6.2.4/macos/mkspecs/common/clang.conf:
../Desktop/QT/6.2.4/macos/mkspecs/common/clang-mac.conf:
../Desktop/QT/6.2.4/macos/mkspecs/qconfig.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_ext_freetype.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_ext_libpng.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_concurrent.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_core.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_core_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_dbus.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designer.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designer_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_gui.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_gui_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_help.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_help_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssettings.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_linguist.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_network.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_network_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_opengl.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_printsupport.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qml.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qml_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmltest.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quick.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quick_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_sql.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_sql_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svg.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svg_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_testlib.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_tools_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uitools.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_widgets.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_xml.pri:
../Desktop/QT/6.2.4/macos/mkspecs/modules/qt_lib_xml_private.pri:
../Desktop/QT/6.2.4/macos/mkspecs/features/qt_functions.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/qt_config.prf:
../Desktop/QT/6.2.4/macos/mkspecs/macx-clang/qmake.conf:
../Desktop/QT/6.2.4/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../Desktop/QT/6.2.4/macos/mkspecs/features/exclusive_builds.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/mac/sdk.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/toolchain.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/mac/toolchain.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/default_pre.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/mac/default_pre.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/resolve_config.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/default_post.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/mac/default_post.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/mac/objective_c.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/qml_debug.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/mac/mac.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/warn_on.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/qt.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/resources_functions.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/resources.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/moc.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/unix/opengl.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/uic.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/unix/thread.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/qmake_use.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/file_copies.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/mac/rez.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/mac/asset_catalogs.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/testcase_targets.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/exceptions.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/yacc.prf:
../Desktop/QT/6.2.4/macos/mkspecs/features/lex.prf:
../ATM/ATM.pro:
../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../Desktop/QT/6.2.4/macos/lib/QtGui.framework/Resources/QtGui.prl:
../Desktop/QT/6.2.4/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../ATM/ATM.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

ATM.app/Contents/PkgInfo: 
	@test -d ATM.app/Contents || mkdir -p ATM.app/Contents
	@$(DEL_FILE) ATM.app/Contents/PkgInfo
	@echo "APPL????" > ATM.app/Contents/PkgInfo
ATM.app/Contents/Resources/empty.lproj: 
	@test -d ATM.app/Contents/Resources || mkdir -p ATM.app/Contents/Resources
	@touch ATM.app/Contents/Resources/empty.lproj
	
ATM.app/Contents/Info.plist: 
	@test -d ATM.app/Contents || mkdir -p ATM.app/Contents
	@$(DEL_FILE) ATM.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,cysgcys.ATM,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},cysgcys.ATM,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,ATM,g" -e "s,@LIBRARY@,ATM,g" -e "s,\$${EXECUTABLE_NAME},ATM,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../Desktop/QT/6.2.4/macos/mkspecs/macx-clang/Info.plist.app >ATM.app/Contents/Info.plist

all: Makefile \
		ATM.app/Contents/PkgInfo \
		ATM.app/Contents/Resources/empty.lproj \
		ATM.app/Contents/Info.plist ATM.app/Contents/MacOS/ATM

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../ATM/mainwindow.h ../ATM/transactions.h $(DISTDIR)/
	$(COPY_FILE) --parents ../ATM/main.cpp ../ATM/mainwindow.cpp ../ATM/transactions.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../ATM/mainwindow.ui ../ATM/transactions.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ATM.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_transactions.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_transactions.cpp
moc_mainwindow.cpp: ../ATM/mainwindow.h \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Desktop/QT/6.2.4/macos/libexec/moc
	/Users/macbook/Desktop/QT/6.2.4/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/macbook/Desktop/QT/6.2.4/macos/mkspecs/macx-clang -I/Users/macbook/ATM -I/Users/macbook/Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers -I/Users/macbook/Desktop/QT/6.2.4/macos/lib/QtGui.framework/Headers -I/Users/macbook/Desktop/QT/6.2.4/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/macbook/Desktop/QT/6.2.4/macos/lib ../ATM/mainwindow.h -o moc_mainwindow.cpp

moc_transactions.cpp: ../ATM/transactions.h \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../Desktop/QT/6.2.4/macos/libexec/moc
	/Users/macbook/Desktop/QT/6.2.4/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/macbook/Desktop/QT/6.2.4/macos/mkspecs/macx-clang -I/Users/macbook/ATM -I/Users/macbook/Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers -I/Users/macbook/Desktop/QT/6.2.4/macos/lib/QtGui.framework/Headers -I/Users/macbook/Desktop/QT/6.2.4/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/macbook/Desktop/QT/6.2.4/macos/lib ../ATM/transactions.h -o moc_transactions.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_transactions.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_transactions.h
ui_mainwindow.h: ../ATM/mainwindow.ui \
		../Desktop/QT/6.2.4/macos/libexec/uic
	/Users/macbook/Desktop/QT/6.2.4/macos/libexec/uic ../ATM/mainwindow.ui -o ui_mainwindow.h

ui_transactions.h: ../ATM/transactions.ui \
		../Desktop/QT/6.2.4/macos/libexec/uic
	/Users/macbook/Desktop/QT/6.2.4/macos/libexec/uic ../ATM/transactions.ui -o ui_transactions.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../ATM/main.cpp ../ATM/mainwindow.h \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/QApplication \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../ATM/main.cpp

mainwindow.o: ../ATM/mainwindow.cpp ../ATM/mainwindow.h \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		../ATM/transactions.h \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../ATM/mainwindow.cpp

transactions.o: ../ATM/transactions.cpp ../ATM/transactions.h \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Desktop/QT/6.2.4/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_transactions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transactions.o ../ATM/transactions.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_transactions.o: moc_transactions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transactions.o moc_transactions.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ATM/bin || mkdir -p $(INSTALL_ROOT)/opt/ATM/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ATM/bin/ATM.app
	
	$(QINSTALL) ATM.app $(INSTALL_ROOT)/opt/ATM/bin/ATM.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ATM/bin/ATM.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ATM/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

